Add onOpenUri
ch4rl3x/HtmlText pull request #7
Opened 2023-01-07 16:48 UTC by S-H-Y-A

Added "onOpenUri" to hook opening uri.

2023-01-19 07:06 UTC, ch4rl3x commented on html-text/src/main/java/de/charlex/compose/HtmlText.kt
> +    onOpenUri: (label: String, uri: String, uriHandler: UriHandler) -> Unit = { _, uri, uriHandler -> uriHandler.openUri(uri)},
Could you rename the callback to onLinkClicked?

2023-01-19 07:17 UTC, ch4rl3x requested changes
A few changes

2023-01-19 07:17 UTC, ch4rl3x commented on html-text/src/main/java/de/charlex/compose/HtmlText.kt
> +    onOpenUri: (label: String, uri: String, uriHandler: UriHandler) -> Unit = { _, uri, uriHandler -> uriHandler.openUri(uri)},
Could you rename the callback to onLinkClicked?

2023-01-19 07:17 UTC, ch4rl3x commented on html-text/src/main/java/de/charlex/compose/HtmlText.kt
> +    onOpenUri: (label: String, uri: String, uriHandler: UriHandler) -> Unit = { _, uri, uriHandler -> uriHandler.openUri(uri)},
Maybe better du remove UriHandler from callback and make the callback nullable with default as null. Within th function use `onLinkClicked?.invoke(annotatedString.substring(sa.start, sa.end), sa.item) ?: uriHandler.openUri(sa.item)`

2023-01-19 07:17 UTC, ch4rl3x commented on html-text/src/main/java/de/charlex/compose/HtmlText.kt
> +    onOpenUri: (label: String, uri: String, uriHandler: UriHandler) -> Unit = { _, uri, uriHandler -> uriHandler.openUri(uri)},
Same here

2023-01-19 07:17 UTC, ch4rl3x commented on html-text/src/main/java/de/charlex/compose/HtmlText.kt
> +                                onOpenUri.invoke(
As described something like `onLinkClicked?.invoke(annotatedString.substring(sa.start, sa.end), sa.item) ?: uriHandler.openUri(sa.item)`

2023-01-19 07:17 UTC, ch4rl3x commented on html-text/src/main/java/de/charlex/compose/HtmlText.kt
> +                    onOpenUri.invoke(
Same here

2023-01-19 07:17 UTC, ch4rl3x commented on html-text/src/main/java/de/charlex/compose/HtmlText.kt
> +                        onOpenUri.invoke(
Same here

2023-01-26 09:02 UTC, S-H-Y-A commented
Check please.

2023-02-16 08:19 UTC, ch4rl3x approved these changes

2023-09-07 19:47 UTC, closed without merging

2023-09-07 19:48 UTC, ch4rl3x commented
Solved with #12